### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by tobrun** [AgeOfMobile/flutter_mapbox#1]
Seeing the following error when running the sample project with following configuration:

> Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b397406561 (3 weeks ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

```
E/flutter (31174): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (31174): type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' where
E/flutter (31174):   _InternalLinkedHashMap is from dart:collection
E/flutter (31174):   Map is from dart:core
E/flutter (31174):   String is from dart:core
E/flutter (31174): 
E/flutter (31174): #0      MapboxMap.create (package:flutter_mapbox/mapbox_map.dart)
E/flutter (31174): <asynchronous suspension>
E/flutter (31174): #1      MapViewState._createMapView (package:flutter_mapbox/map_view.dart:26:40)
E/flutter (31174): <asynchronous suspension>
E/flutter (31174): #2      MapViewState.build.<anonymous closure> (package:flutter_mapbox/map_view.dart:51:9)
E/flutter (31174): #3      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:111:26)
E/flutter (31174): #4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
E/flutter (31174): #5      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
E/flutter (31174): #6      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
E/flutter (31174): #7      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
E/flutter (31174): #8      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
E/flutter (31174): #9      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
E/flutter (31174): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #11     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
E/flutter (31174): #12     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
E/flutter (31174): #13     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
E/flutter (31174): #14     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
E/flutter (31174): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
E/flutter (31174): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
E/flutter (31174): #19     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1141:11)
E/flutter (31174): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
E/flutter (31174): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
E/flutter (31174): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
E/flutter (31174): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
E/flutter (31174): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
E/flutter (31174): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
E/flutter (31174): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (31174): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
E/flutter (31174): #34     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2716:13)
E/flutter (31174): #35     RenderObject.layout (package:flutter/src/rendering

**Comment by tribui** [comment]
Fixed
